name = "url-shortener"
compatibility_date = "2025-01-13"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

[vars]
CLOUDFLARE_ACCOUNT_ID = "f1fcf5d3ced88a2c5fd17f922883dead"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[kv_namespaces]]
binding = "URL_SHORTENER"
id = "bb6d1324193d4c86bdbe46b0033837fd"
preview_id = "559964fc399245f0bbd97066633329c9"

[[analytics_engine_datasets]]
binding = "TRACKER"
dataset = "link_clicks"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
